set nocompatible                " choose no compatibility with legacy vi

" Leader
let mapleader=" "

" set fillchars+=stl:\ ,stlnc:\
" set fillchars=stl:―,stlnc:—,vert:│,fold:۰,diff:·
" set term=xterm-256color
" set termencoding=utf-8

filetype off                    " required for vundle
set rtp+=~/.vim/bundle/vundle/  " required for vundle
call vundle#begin()

Plugin 'gmarik/vundle'

" --- Motion utilities
Plugin 'vim-scripts/matchit.zip'
Plugin 'Lokaltog/vim-easymotion'
Plugin 'ctrlpvim/ctrlp.vim'

" --- Interface tweaks
" Plugin 'Lokaltog/vim-powerline'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
" Plugin 'edkolev/tmuxline.vim'
" Plugin 'vim-perl/vim-perl'
Plugin 'sjl/vitality.vim'
Plugin 'altercation/vim-colors-solarized'
Plugin 'chriskempson/base16-vim'
"Plugin 'tomasr/molokai'
"Plugin 'morhetz/gruvbox'
"Plugin 'sjl/badwolf'
"Plugin 'nanotech/jellybeans.vim'

" --- Ruby utils
Plugin 'vim-scripts/ruby-matchit'
Plugin 'vim-ruby/vim-ruby'
Plugin 'tpope/vim-rails'
Plugin 'tpope/vim-endwise'
Plugin 'kchmck/vim-coffee-script'
"Plugin 'tpope/vim-bundler'                  " Bundler utils

" --- General dev utils
Plugin 'airblade/vim-gitgutter'
Plugin 'scrooloose/syntastic'
Plugin 'tpope/vim-fugitive'
Plugin 'ervandew/supertab'
Plugin 'godlygeek/tabular'
Plugin 'majutsushi/tagbar'
Plugin 'tpope/vim-surround'
Plugin 'scrooloose/nerdtree'
Plugin 'scrooloose/nerdcommenter'
Plugin 'mileszs/ack.vim'
Plugin 'kana/vim-smartinput'
Plugin 'Yggdroot/indentLine'
Plugin 'Keithbsmiley/investigate.vim'
Plugin 'benmills/vimux'
Plugin 'jgdavey/vim-turbux'
"Plugin 'tpope/vim-unimpaired'

call vundle#end()               " required for vundle

"au BufWritePost .vimrc so ~/.vimrc " automatically reload vimrc when it's saved

"" Some general editor stuff
"set clipboard=unnamed           " send yanks to the OS clipboard
"set mouse=a
set nobackup                    " Do not keep a backup file
set encoding=utf-8
set showcmd                     " display incomplete commands
set scrolloff=7                 " Never scroll to the edge of the window
set history=50                  " Keep the last 50 commands
set t_ti= t_te=                 " Do not clear the screen when exiting vim, and preserve the window
au FocusLost * :silent! wall    " Autosave on losing focus (works in iTerms2 and tmux using VITality plugin)
syntax enable
set synmaxcol=250               " limits syntax highlight to first 250 columns, to prevent slow down on long lines"
filetype plugin indent on       " load file type plugins + indentation

" Store temporary files in a central spot
set backupdir=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp
set directory=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp

"" Folding
set nofoldenable
set foldmethod=indent
set foldlevelstart=20

"" Whitespace
set nowrap                      " don't wrap lines
set tabstop=2 shiftwidth=2      " a tab is two spaces (or set this to 4)
set expandtab                   " use spaces, not tabs (optional)
set shiftround                  " Always indent/outdent to nearest tabstop
set backspace=indent,eol,start  " backspace through everything in insert mode
set pastetoggle=<leader>pt      " "Set  to toggle paste on and off.

"" Searching
set hlsearch                    " highlight matches
set incsearch                   " incremental searching
set ignorecase                  " searches are case insensitive...
set smartcase                   " ... unless they contain at least one capital letter
set gdefault                    " Make global search and replace the default (use /g to make it singular)
set wildmenu
set wildignore+=*/.hg/*,*/.svn/*,*.swp,*.swo

"" Editor window dressing
let base16colorspace=256  " Access colors present in 256 colorspace
colorscheme base16-tomorrow
" colorscheme base16-solarized
" colorscheme base16-eighties
" colorscheme base16-ocean
" colorscheme base16-monokai

" colorscheme solarized
set t_Co=256                    " 256 colours
set cursorline                  " Highlight current line
set ruler                       " Show a ruler
set number                      " Show line numbers
set relativenumber              " Show lines numbers relative to where you are
" au InsertEnter * :set nu        " absolute line numbers in insert mode,
" au InsertLeave * :set rnu       " relative otherwise for easy movement
set showmatch                   " Show matching brackets
set guifont=Inconsolata:h18     "Set the font to Inconsolata at 18pt. (Yes, it's huge)
set bg=dark                     " Dark background
"set bg=light                    " Light background
set listchars=tab:▸\ ,eol:¬,trail:⋅,extends:❯,precedes:❮ " Make the list chars less hideous (and more like textmate)
set showbreak=↪

function! CurDir()
  let curdir = substitute(getcwd(), '/home/nileshn/', "~/", "g")
  return curdir
endfunction
set laststatus=2                " Show statusline on second last line
set statusline=\ [%F%m%r%h\ %w]\ \ \ [CWD:%r%{CurDir()}%h]\ \ \ [Type=%Y]\ \ \ %{fugitive#statusline()}\ \ \ [Line:%l/%L:%c\ %p%%]\ 

"" Tab shortcuts
map <leader>tn :tabnew 
map <leader>tm :tabmove 
map <leader>te :tabe 
map <leader>tc :tabclose<cr>    " Close
map <leader><right> :tabn<cr>   " Select tab to the right
map <leader><left> :tabp<cr>    " Select tab to the left
map <leader>k :tabn<cr>         " Select tab to the right using k
map <leader>j :tabp<cr>         " Select tab to the left using j

"" Open v-split on right & h-split at bottom
" set splitbelow
set splitright

"" Split window shortcuts
nmap <silent> <A-Up> :wincmd k<CR>
nmap <silent> <A-Down> :wincmd j<CR>
nmap <silent> <A-Left> :wincmd h<CR>
nmap <silent> <A-Right> :wincmd l<CR>

"" Be clever about pasting from somewhere into the terminal
"" This detects a paste from the pasteboard and will temporarily
"" set pastetoggle
"" Doesn't work with things like tmux and screen
"if &term =~ "xterm.*"
    "let &t_ti = &t_ti . "\e[?2004h"
    "let &t_te = "\e[?2004l" . &t_te
    "function XTermPasteBegin(ret)
        "set pastetoggle=<Esc>[201~
        "set paste
        "return a:ret
    "endfunction
    "map <expr> <Esc>[200~ XTermPasteBegin("i")
    "imap <expr> <Esc>[200~ XTermPasteBegin("")
    "cmap <Esc>[200~ <nop>
    "cmap <Esc>[201~ <nop>
"endif

"" Make vim jump to the last known line
if has("autocmd")
  au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
    \| exe "normal! g'\"" | endif
endif

"" Fix silly typos to DWIM, not DWIS
"cmap W w
cmap Q q

"" Load up bundle specfic configuration
""  -- doesn't clutter up the rest of the vimrc this way.
runtime! bundle_config/*.vim

""" Highlight trailing whitespace
"highlight TrailWhitespace ctermbg=red guibg=red
"match TrailWhitespace /\s\+$\| \+\ze\t/

" Speed up start times when dealing with Ruby files
" For rbenv
let g:ruby_path = system('echo $HOME/.rbenv/shims')
" For rvm
"let g:ruby_path = system('rvm current')

" Abbreviations
iabbrev trye true
