if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi

# To remove duplicates on path
# remove /usr/local/bin and /usr/bin
#export PATH=`echo ":$PATH:" | sed -e "s:\:/usr/local/bin\::\::g" -e "s/^://" -e "s/:$//"`
#export PATH=`echo ":$PATH:" | sed -e "s:\:/usr/bin\::\::g" -e "s/^://" -e "s/:$//"`
# add /usr/local/bin and /usr/bin in that order
#export PATH="/usr/local/bin:/usr/bin:$PATH"

# This puts homebrew packages first in path
# export PATH="/usr/local/bin:$PATH"
export PATH="/usr/local/bin:/usr/local/sbin:$PATH"

# Set CLICOLOR if you want Ansi Colors in iTerm2 
export CLICOLOR=1

# Set colors to match iTerm2 Terminal Colors
export TERM=xterm-256color

if [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi

## Setup for rbenv
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

## Setup for node.js
# export PATH="$PATH:/usr/local/lib/node_modules"
export NVM_DIR=~/.nvm
source $(brew --prefix nvm)/nvm.sh

## Setup for python

# pip should only run if there is a virtualenv currently activated
export PIP_REQUIRE_VIRTUALENV=true
# cache pip-installed packages to avoid re-downloading
export PIP_DOWNLOAD_CACHE=$HOME/.pip/cache
